namespace HRM.Winform.Forms.CaNhan
{
    partial class FrmChamCongThongMinh
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private Panel pnlTop;
        private Label lblTitle;
        private Label lblSubtitle;
        private Label lblLastSync;
        private FlowLayoutPanel pnlMethods;
        private Button btnKhuonMat;
        private Button btnQr;
        private Button btnGps;
        private Button btnCheckOut;
        private Button btnLamMoi;
        private TableLayoutPanel tlpSummary;
        private Panel pnlStatus;
        private Label lblStatusTitle;
        private Label lblStatusValue;
        private Label lblStatusDetail;
        private Panel pnlShift;
        private Label lblShiftTitle;
        private Label lblShiftValue;
        private Label lblShiftDetail;
        private Panel pnlReminder;
        private Label lblReminderTitle;
        private Label lblReminderValue;
        private Label lblReminderDetail;
        private Panel pnlStats;
        private Label lblStatsTitle;
        private Label lblStatsValue;
        private Label lblStatsDetail;
        private Panel pnlHistory;
        private Label lblHistory;
        private DataGridView dgvHistory;
        private Panel pnlNotifications;
        private Label lblNotificationsTitle;
        private FlowLayoutPanel flpNotifications;

        private void InitializeComponent()
        {
            pnlTop = new Panel();
            btnLamMoi = new Button();
            pnlMethods = new FlowLayoutPanel();
            btnKhuonMat = new Button();
            btnQr = new Button();
            btnGps = new Button();
            btnCheckOut = new Button();
            lblLastSync = new Label();
            lblSubtitle = new Label();
            lblTitle = new Label();
            tlpSummary = new TableLayoutPanel();
            pnlStatus = new Panel();
            lblStatusDetail = new Label();
            lblStatusValue = new Label();
            lblStatusTitle = new Label();
            pnlShift = new Panel();
            lblShiftDetail = new Label();
            lblShiftValue = new Label();
            lblShiftTitle = new Label();
            pnlReminder = new Panel();
            lblReminderDetail = new Label();
            lblReminderValue = new Label();
            lblReminderTitle = new Label();
            pnlStats = new Panel();
            lblStatsDetail = new Label();
            lblStatsValue = new Label();
            lblStatsTitle = new Label();
            pnlNotifications = new Panel();
            flpNotifications = new FlowLayoutPanel();
            lblNotificationsTitle = new Label();
            pnlHistory = new Panel();
            dgvHistory = new DataGridView();
            lblHistory = new Label();
            pnlTop.SuspendLayout();
            pnlMethods.SuspendLayout();
            tlpSummary.SuspendLayout();
            pnlStatus.SuspendLayout();
            pnlShift.SuspendLayout();
            pnlReminder.SuspendLayout();
            pnlStats.SuspendLayout();
            pnlHistory.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)dgvHistory).BeginInit();
            SuspendLayout();
            pnlTop.Controls.Add(btnLamMoi);
            pnlTop.Controls.Add(pnlMethods);
            pnlTop.Controls.Add(lblLastSync);
            pnlTop.Controls.Add(lblSubtitle);
            pnlTop.Controls.Add(lblTitle);
            pnlTop.Dock = DockStyle.Top;
            pnlTop.Location = new Point(0, 0);
            pnlTop.Name = "pnlTop";
            pnlTop.Padding = new Padding(24, 22, 24, 18);
            pnlTop.Size = new Size(1184, 170);
            btnLamMoi.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            btnLamMoi.Location = new Point(1047, 22);
            btnLamMoi.Name = "btnLamMoi";
            btnLamMoi.Size = new Size(110, 38);
            btnLamMoi.TabIndex = 4;
            btnLamMoi.Text = "Lam moi";
            btnLamMoi.Click += btnLamMoi_Click;
            pnlMethods.Controls.Add(btnKhuonMat);
            pnlMethods.Controls.Add(btnQr);
            pnlMethods.Controls.Add(btnGps);
            pnlMethods.Controls.Add(btnCheckOut);
            pnlMethods.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            pnlMethods.Location = new Point(24, 90);
            pnlMethods.Name = "pnlMethods";
            pnlMethods.Size = new Size(860, 48);
            pnlMethods.WrapContents = true;
            btnKhuonMat.Location = new Point(0, 0);
            btnKhuonMat.Margin = new Padding(0, 0, 12, 0);
            btnKhuonMat.Name = "btnKhuonMat";
            btnKhuonMat.Size = new Size(170, 42);
            btnKhuonMat.Text = "Check in khuon mat";
            btnKhuonMat.Click += btnKhuonMat_Click;
            btnQr.Location = new Point(182, 0);
            btnQr.Margin = new Padding(0, 0, 12, 0);
            btnQr.Name = "btnQr";
            btnQr.Size = new Size(150, 42);
            btnQr.Text = "Check in QR";
            btnQr.Click += btnQr_Click;
            btnGps.Location = new Point(344, 0);
            btnGps.Margin = new Padding(0, 0, 12, 0);
            btnGps.Name = "btnGps";
            btnGps.Size = new Size(150, 42);
            btnGps.Text = "Check in GPS";
            btnGps.Click += btnGps_Click;
            btnCheckOut.Location = new Point(506, 0);
            btnCheckOut.Margin = new Padding(0);
            btnCheckOut.Name = "btnCheckOut";
            btnCheckOut.Size = new Size(150, 42);
            btnCheckOut.Text = "Check out";
            btnCheckOut.Click += btnCheckOut_Click;
            lblLastSync.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            lblLastSync.AutoSize = true;
            lblLastSync.Location = new Point(893, 111);
            lblLastSync.Name = "lblLastSync";
            lblLastSync.Size = new Size(135, 20);
            lblLastSync.Text = "Cap nhat luc --:--";
            lblSubtitle.AutoSize = true;
            lblSubtitle.Location = new Point(24, 52);
            lblSubtitle.Name = "lblSubtitle";
            lblSubtitle.Size = new Size(410, 20);
            lblSubtitle.Text = "Cham cong bang khuon mat, QR, GPS va theo doi nhac viec ca nhan.";
            lblTitle.AutoSize = true;
            lblTitle.Font = new Font("Segoe UI", 18F, FontStyle.Bold);
            lblTitle.Location = new Point(24, 11);
            lblTitle.Name = "lblTitle";
            lblTitle.Size = new Size(311, 41);
            lblTitle.Text = "Cham cong thong minh";
            tlpSummary.ColumnCount = 2;
            tlpSummary.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            tlpSummary.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            tlpSummary.Controls.Add(pnlStatus, 0, 0);
            tlpSummary.Controls.Add(pnlShift, 1, 0);
            tlpSummary.Controls.Add(pnlReminder, 0, 1);
            tlpSummary.Controls.Add(pnlStats, 1, 1);
            tlpSummary.Dock = DockStyle.Top;
            tlpSummary.Location = new Point(0, 170);
            tlpSummary.Name = "tlpSummary";
            tlpSummary.Padding = new Padding(24, 20, 24, 0);
            tlpSummary.RowCount = 2;
            tlpSummary.RowStyles.Add(new RowStyle(SizeType.Absolute, 124F));
            tlpSummary.RowStyles.Add(new RowStyle(SizeType.Absolute, 124F));
            tlpSummary.Size = new Size(1184, 268);
            pnlStatus.Controls.Add(lblStatusDetail);
            pnlStatus.Controls.Add(lblStatusValue);
            pnlStatus.Controls.Add(lblStatusTitle);
            pnlStatus.Dock = DockStyle.Fill;
            pnlStatus.Padding = new Padding(18);
            lblStatusDetail.Dock = DockStyle.Fill;
            lblStatusDetail.Location = new Point(18, 70);
            lblStatusDetail.Text = "--";
            lblStatusValue.Dock = DockStyle.Top;
            lblStatusValue.Font = new Font("Segoe UI", 16F, FontStyle.Bold);
            lblStatusValue.Location = new Point(18, 34);
            lblStatusValue.Text = "Chua check in";
            lblStatusTitle.Dock = DockStyle.Top;
            lblStatusTitle.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            lblStatusTitle.Location = new Point(18, 18);
            lblStatusTitle.Text = "Trang thai hom nay";
            pnlShift.Controls.Add(lblShiftDetail);
            pnlShift.Controls.Add(lblShiftValue);
            pnlShift.Controls.Add(lblShiftTitle);
            pnlShift.Dock = DockStyle.Fill;
            pnlShift.Padding = new Padding(18);
            lblShiftDetail.Dock = DockStyle.Fill;
            lblShiftDetail.Location = new Point(18, 70);
            lblShiftDetail.Text = "--";
            lblShiftValue.Dock = DockStyle.Top;
            lblShiftValue.Font = new Font("Segoe UI", 16F, FontStyle.Bold);
            lblShiftValue.Location = new Point(18, 34);
            lblShiftValue.Text = "Chua phan ca";
            lblShiftTitle.Dock = DockStyle.Top;
            lblShiftTitle.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            lblShiftTitle.Location = new Point(18, 18);
            lblShiftTitle.Text = "Ca lam viec";
            pnlReminder.Controls.Add(lblReminderDetail);
            pnlReminder.Controls.Add(lblReminderValue);
            pnlReminder.Controls.Add(lblReminderTitle);
            pnlReminder.Dock = DockStyle.Fill;
            pnlReminder.Padding = new Padding(18);
            lblReminderDetail.Dock = DockStyle.Fill;
            lblReminderDetail.Location = new Point(18, 70);
            lblReminderDetail.Text = "--";
            lblReminderValue.Dock = DockStyle.Top;
            lblReminderValue.Font = new Font("Segoe UI", 14F, FontStyle.Bold);
            lblReminderValue.Location = new Point(18, 34);
            lblReminderValue.Text = "Nhac viec";
            lblReminderTitle.Dock = DockStyle.Top;
            lblReminderTitle.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            lblReminderTitle.Location = new Point(18, 18);
            lblReminderTitle.Text = "Nhac thong minh";
            pnlStats.Controls.Add(lblStatsDetail);
            pnlStats.Controls.Add(lblStatsValue);
            pnlStats.Controls.Add(lblStatsTitle);
            pnlStats.Dock = DockStyle.Fill;
            pnlStats.Padding = new Padding(18);
            lblStatsDetail.Dock = DockStyle.Fill;
            lblStatsDetail.Location = new Point(18, 70);
            lblStatsDetail.Text = "--";
            lblStatsValue.Dock = DockStyle.Top;
            lblStatsValue.Font = new Font("Segoe UI", 16F, FontStyle.Bold);
            lblStatsValue.Location = new Point(18, 34);
            lblStatsValue.Text = "0 gio";
            lblStatsTitle.Dock = DockStyle.Top;
            lblStatsTitle.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            lblStatsTitle.Location = new Point(18, 18);
            lblStatsTitle.Text = "Tong quan thang nay";
            pnlNotifications.Controls.Add(flpNotifications);
            pnlNotifications.Controls.Add(lblNotificationsTitle);
            pnlNotifications.Dock = DockStyle.Top;
            pnlNotifications.Location = new Point(0, 438);
            pnlNotifications.Name = "pnlNotifications";
            pnlNotifications.Padding = new Padding(24, 20, 24, 12);
            pnlNotifications.Size = new Size(1184, 184);
            flpNotifications.AutoScroll = true;
            flpNotifications.Dock = DockStyle.Fill;
            flpNotifications.FlowDirection = FlowDirection.TopDown;
            flpNotifications.Location = new Point(24, 50);
            flpNotifications.Name = "flpNotifications";
            flpNotifications.Padding = new Padding(0, 2, 0, 0);
            flpNotifications.Size = new Size(1136, 122);
            flpNotifications.WrapContents = false;
            lblNotificationsTitle.Dock = DockStyle.Top;
            lblNotificationsTitle.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
            lblNotificationsTitle.Location = new Point(24, 20);
            lblNotificationsTitle.Size = new Size(1136, 30);
            lblNotificationsTitle.Text = "Thong bao ca nhan";
            pnlHistory.Controls.Add(dgvHistory);
            pnlHistory.Controls.Add(lblHistory);
            pnlHistory.Dock = DockStyle.Fill;
            pnlHistory.Location = new Point(0, 622);
            pnlHistory.Name = "pnlHistory";
            pnlHistory.Padding = new Padding(24, 20, 24, 24);
            pnlHistory.Size = new Size(1184, 139);
            dgvHistory.Dock = DockStyle.Fill;
            dgvHistory.Location = new Point(24, 48);
            dgvHistory.Name = "dgvHistory";
            dgvHistory.RowHeadersWidth = 51;
            dgvHistory.Size = new Size(1136, 251);
            lblHistory.Dock = DockStyle.Top;
            lblHistory.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
            lblHistory.Location = new Point(24, 20);
            lblHistory.Size = new Size(1136, 28);
            lblHistory.Text = "Lich su cham cong gan day";
            AutoScaleDimensions = new SizeF(8F, 20F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(1184, 761);
            Controls.Add(pnlHistory);
            Controls.Add(pnlNotifications);
            Controls.Add(tlpSummary);
            Controls.Add(pnlTop);
            MinimumSize = new Size(980, 680);
            Name = "FrmChamCongThongMinh";
            Text = "Cham cong thong minh";
            Load += FrmChamCongThongMinh_Load;
            pnlTop.ResumeLayout(false);
            pnlTop.PerformLayout();
            pnlMethods.ResumeLayout(false);
            tlpSummary.ResumeLayout(false);
            pnlStatus.ResumeLayout(false);
            pnlShift.ResumeLayout(false);
            pnlReminder.ResumeLayout(false);
            pnlStats.ResumeLayout(false);
            pnlNotifications.ResumeLayout(false);
            pnlHistory.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)dgvHistory).EndInit();
            ResumeLayout(false);
        }
    }
}
