namespace HRM.Winform.Forms.CaNhan
{
    partial class FrmDonTuCaNhan
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private Panel pnlTop;
        private Label lblTitle;
        private Label lblTongDonNghiText;
        private Label lblTongDonNghi;
        private Label lblTongDonTangCaText;
        private Label lblTongDonTangCa;
        private TabControl tabMain;
        private TabPage tabNghiPhep;
        private TabPage tabTangCa;
        private TabPage tabDieuChinh;
        private ComboBox cboLoaiNghi;
        private Label lblLoaiNghi;
        private DateTimePicker dtpTuNgayNghi;
        private DateTimePicker dtpDenNgayNghi;
        private Label lblTuNgayNghi;
        private Label lblDenNgayNghi;
        private NumericUpDown nudTongSoNgay;
        private Button btnTinhSoNgay;
        private Label lblTongSoNgay;
        private TextBox txtLyDoNghi;
        private Label lblLyDoNghi;
        private ComboBox cboTrangThaiNghi;
        private Label lblTrangThaiNghi;
        private Button btnGuiNghiPhep;
        private DataGridView dgvNghiPhep;
        private DateTimePicker dtpNgayTangCa;
        private DateTimePicker dtpTuGioTangCa;
        private DateTimePicker dtpDenGioTangCa;
        private Label lblNgayTangCa;
        private Label lblTuGioTangCa;
        private Label lblDenGioTangCa;
        private TextBox txtLyDoTangCa;
        private Label lblLyDoTangCa;
        private ComboBox cboTrangThaiTangCa;
        private Label lblTrangThaiTangCa;
        private Button btnGuiTangCa;
        private DataGridView dgvTangCa;
        private Label lblDieuChinh;
        private TextBox txtDieuChinh;
        private Button btnGuiDieuChinh;
        private Label lblDieuChinhNote;

        private void InitializeComponent()
        {
            pnlTop = new Panel();
            lblTongDonTangCa = new Label();
            lblTongDonTangCaText = new Label();
            lblTongDonNghi = new Label();
            lblTongDonNghiText = new Label();
            lblTitle = new Label();
            tabMain = new TabControl();
            tabNghiPhep = new TabPage();
            dgvNghiPhep = new DataGridView();
            btnGuiNghiPhep = new Button();
            cboTrangThaiNghi = new ComboBox();
            lblTrangThaiNghi = new Label();
            txtLyDoNghi = new TextBox();
            lblLyDoNghi = new Label();
            btnTinhSoNgay = new Button();
            nudTongSoNgay = new NumericUpDown();
            lblTongSoNgay = new Label();
            dtpDenNgayNghi = new DateTimePicker();
            lblDenNgayNghi = new Label();
            dtpTuNgayNghi = new DateTimePicker();
            lblTuNgayNghi = new Label();
            cboLoaiNghi = new ComboBox();
            lblLoaiNghi = new Label();
            tabTangCa = new TabPage();
            dgvTangCa = new DataGridView();
            btnGuiTangCa = new Button();
            cboTrangThaiTangCa = new ComboBox();
            lblTrangThaiTangCa = new Label();
            txtLyDoTangCa = new TextBox();
            lblLyDoTangCa = new Label();
            dtpDenGioTangCa = new DateTimePicker();
            lblDenGioTangCa = new Label();
            dtpTuGioTangCa = new DateTimePicker();
            lblTuGioTangCa = new Label();
            dtpNgayTangCa = new DateTimePicker();
            lblNgayTangCa = new Label();
            tabDieuChinh = new TabPage();
            lblDieuChinhNote = new Label();
            btnGuiDieuChinh = new Button();
            txtDieuChinh = new TextBox();
            lblDieuChinh = new Label();
            pnlTop.SuspendLayout();
            tabMain.SuspendLayout();
            tabNghiPhep.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)dgvNghiPhep).BeginInit();
            ((System.ComponentModel.ISupportInitialize)nudTongSoNgay).BeginInit();
            tabTangCa.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)dgvTangCa).BeginInit();
            tabDieuChinh.SuspendLayout();
            SuspendLayout();
            pnlTop.Controls.Add(lblTongDonTangCa);
            pnlTop.Controls.Add(lblTongDonTangCaText);
            pnlTop.Controls.Add(lblTongDonNghi);
            pnlTop.Controls.Add(lblTongDonNghiText);
            pnlTop.Controls.Add(lblTitle);
            pnlTop.Dock = DockStyle.Top;
            pnlTop.Padding = new Padding(24, 18, 24, 14);
            pnlTop.Size = new Size(1184, 90);
            lblTongDonTangCa.AutoSize = true;
            lblTongDonTangCa.Font = new Font("Segoe UI", 14F, FontStyle.Bold);
            lblTongDonTangCa.Location = new Point(987, 29);
            lblTongDonTangCa.Text = "0";
            lblTongDonTangCaText.AutoSize = true;
            lblTongDonTangCaText.Location = new Point(837, 37);
            lblTongDonTangCaText.Text = "Tong don tang ca:";
            lblTongDonNghi.AutoSize = true;
            lblTongDonNghi.Font = new Font("Segoe UI", 14F, FontStyle.Bold);
            lblTongDonNghi.Location = new Point(745, 29);
            lblTongDonNghi.Text = "0";
            lblTongDonNghiText.AutoSize = true;
            lblTongDonNghiText.Location = new Point(613, 37);
            lblTongDonNghiText.Text = "Tong don nghi:";
            lblTitle.AutoSize = true;
            lblTitle.Font = new Font("Segoe UI", 18F, FontStyle.Bold);
            lblTitle.Location = new Point(24, 24);
            lblTitle.Text = "Don tu cua toi";
            tabMain.Controls.Add(tabNghiPhep);
            tabMain.Controls.Add(tabTangCa);
            tabMain.Controls.Add(tabDieuChinh);
            tabMain.Dock = DockStyle.Fill;
            tabMain.Location = new Point(0, 90);
            tabMain.Size = new Size(1184, 671);
            tabNghiPhep.Controls.Add(dgvNghiPhep);
            tabNghiPhep.Controls.Add(btnGuiNghiPhep);
            tabNghiPhep.Controls.Add(cboTrangThaiNghi);
            tabNghiPhep.Controls.Add(lblTrangThaiNghi);
            tabNghiPhep.Controls.Add(txtLyDoNghi);
            tabNghiPhep.Controls.Add(lblLyDoNghi);
            tabNghiPhep.Controls.Add(btnTinhSoNgay);
            tabNghiPhep.Controls.Add(nudTongSoNgay);
            tabNghiPhep.Controls.Add(lblTongSoNgay);
            tabNghiPhep.Controls.Add(dtpDenNgayNghi);
            tabNghiPhep.Controls.Add(lblDenNgayNghi);
            tabNghiPhep.Controls.Add(dtpTuNgayNghi);
            tabNghiPhep.Controls.Add(lblTuNgayNghi);
            tabNghiPhep.Controls.Add(cboLoaiNghi);
            tabNghiPhep.Controls.Add(lblLoaiNghi);
            tabNghiPhep.Padding = new Padding(18);
            tabNghiPhep.Text = "Nghi phep";
            dgvNghiPhep.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            dgvNghiPhep.Location = new Point(21, 227);
            dgvNghiPhep.Size = new Size(1137, 388);
            btnGuiNghiPhep.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            btnGuiNghiPhep.Location = new Point(997, 169);
            btnGuiNghiPhep.Size = new Size(161, 38);
            btnGuiNghiPhep.Text = "Gui don nghi phep";
            btnGuiNghiPhep.Click += btnGuiNghiPhep_Click;
            cboTrangThaiNghi.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            cboTrangThaiNghi.DropDownStyle = ComboBoxStyle.DropDownList;
            cboTrangThaiNghi.FormattingEnabled = true;
            cboTrangThaiNghi.Items.AddRange(new object[] { "ChoDuyet", "DaDuyet", "TuChoi" });
            cboTrangThaiNghi.Location = new Point(908, 41);
            cboTrangThaiNghi.Size = new Size(250, 28);
            lblTrangThaiNghi.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            lblTrangThaiNghi.AutoSize = true;
            lblTrangThaiNghi.Location = new Point(908, 18);
            lblTrangThaiNghi.Text = "Trang thai";
            txtLyDoNghi.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            txtLyDoNghi.Location = new Point(21, 109);
            txtLyDoNghi.Multiline = true;
            txtLyDoNghi.Size = new Size(1137, 42);
            lblLyDoNghi.AutoSize = true;
            lblLyDoNghi.Location = new Point(21, 86);
            lblLyDoNghi.Text = "Ly do";
            btnTinhSoNgay.Location = new Point(649, 168);
            btnTinhSoNgay.Size = new Size(144, 38);
            btnTinhSoNgay.Text = "Tinh so ngay";
            btnTinhSoNgay.Click += btnTinhSoNgay_Click;
            nudTongSoNgay.DecimalPlaces = 1;
            nudTongSoNgay.Location = new Point(454, 175);
            nudTongSoNgay.Minimum = new decimal(new int[] { 1, 0, 0, 0 });
            nudTongSoNgay.Size = new Size(150, 27);
            nudTongSoNgay.Value = new decimal(new int[] { 1, 0, 0, 0 });
            lblTongSoNgay.AutoSize = true;
            lblTongSoNgay.Location = new Point(454, 152);
            lblTongSoNgay.Text = "Tong so ngay";
            dtpDenNgayNghi.Format = DateTimePickerFormat.Short;
            dtpDenNgayNghi.Location = new Point(237, 175);
            dtpDenNgayNghi.Size = new Size(167, 27);
            lblDenNgayNghi.AutoSize = true;
            lblDenNgayNghi.Location = new Point(237, 152);
            lblDenNgayNghi.Text = "Den ngay";
            dtpTuNgayNghi.Format = DateTimePickerFormat.Short;
            dtpTuNgayNghi.Location = new Point(21, 175);
            dtpTuNgayNghi.Size = new Size(167, 27);
            lblTuNgayNghi.AutoSize = true;
            lblTuNgayNghi.Location = new Point(21, 152);
            lblTuNgayNghi.Text = "Tu ngay";
            cboLoaiNghi.DropDownStyle = ComboBoxStyle.DropDownList;
            cboLoaiNghi.Location = new Point(21, 41);
            cboLoaiNghi.Size = new Size(349, 28);
            lblLoaiNghi.AutoSize = true;
            lblLoaiNghi.Location = new Point(21, 18);
            lblLoaiNghi.Text = "Loai nghi";
            tabTangCa.Controls.Add(dgvTangCa);
            tabTangCa.Controls.Add(btnGuiTangCa);
            tabTangCa.Controls.Add(cboTrangThaiTangCa);
            tabTangCa.Controls.Add(lblTrangThaiTangCa);
            tabTangCa.Controls.Add(txtLyDoTangCa);
            tabTangCa.Controls.Add(lblLyDoTangCa);
            tabTangCa.Controls.Add(dtpDenGioTangCa);
            tabTangCa.Controls.Add(lblDenGioTangCa);
            tabTangCa.Controls.Add(dtpTuGioTangCa);
            tabTangCa.Controls.Add(lblTuGioTangCa);
            tabTangCa.Controls.Add(dtpNgayTangCa);
            tabTangCa.Controls.Add(lblNgayTangCa);
            tabTangCa.Padding = new Padding(18);
            tabTangCa.Text = "Tang ca";
            dgvTangCa.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            dgvTangCa.Location = new Point(18, 221);
            dgvTangCa.Size = new Size(1140, 394);
            btnGuiTangCa.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            btnGuiTangCa.Location = new Point(1004, 163);
            btnGuiTangCa.Size = new Size(154, 38);
            btnGuiTangCa.Text = "Gui don tang ca";
            btnGuiTangCa.Click += btnGuiTangCa_Click;
            cboTrangThaiTangCa.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            cboTrangThaiTangCa.DropDownStyle = ComboBoxStyle.DropDownList;
            cboTrangThaiTangCa.FormattingEnabled = true;
            cboTrangThaiTangCa.Items.AddRange(new object[] { "ChoDuyet", "DaDuyet", "TuChoi" });
            cboTrangThaiTangCa.Location = new Point(770, 41);
            cboTrangThaiTangCa.Size = new Size(388, 28);
            lblTrangThaiTangCa.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            lblTrangThaiTangCa.AutoSize = true;
            lblTrangThaiTangCa.Location = new Point(770, 18);
            lblTrangThaiTangCa.Text = "Trang thai";
            txtLyDoTangCa.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            txtLyDoTangCa.Location = new Point(18, 102);
            txtLyDoTangCa.Multiline = true;
            txtLyDoTangCa.Size = new Size(1140, 44);
            lblLyDoTangCa.AutoSize = true;
            lblLyDoTangCa.Location = new Point(18, 79);
            lblLyDoTangCa.Text = "Ly do";
            dtpDenGioTangCa.CustomFormat = "dd/MM/yyyy HH:mm";
            dtpDenGioTangCa.Format = DateTimePickerFormat.Custom;
            dtpDenGioTangCa.Location = new Point(528, 41);
            dtpDenGioTangCa.Size = new Size(202, 27);
            lblDenGioTangCa.AutoSize = true;
            lblDenGioTangCa.Location = new Point(528, 18);
            lblDenGioTangCa.Text = "Den gio";
            dtpTuGioTangCa.CustomFormat = "dd/MM/yyyy HH:mm";
            dtpTuGioTangCa.Format = DateTimePickerFormat.Custom;
            dtpTuGioTangCa.Location = new Point(275, 41);
            dtpTuGioTangCa.Size = new Size(208, 27);
            lblTuGioTangCa.AutoSize = true;
            lblTuGioTangCa.Location = new Point(275, 18);
            lblTuGioTangCa.Text = "Tu gio";
            dtpNgayTangCa.Format = DateTimePickerFormat.Short;
            dtpNgayTangCa.Location = new Point(18, 41);
            dtpNgayTangCa.Size = new Size(212, 27);
            lblNgayTangCa.AutoSize = true;
            lblNgayTangCa.Location = new Point(18, 18);
            lblNgayTangCa.Text = "Ngay lam";
            tabDieuChinh.Controls.Add(lblDieuChinhNote);
            tabDieuChinh.Controls.Add(btnGuiDieuChinh);
            tabDieuChinh.Controls.Add(txtDieuChinh);
            tabDieuChinh.Controls.Add(lblDieuChinh);
            tabDieuChinh.Padding = new Padding(24);
            tabDieuChinh.Text = "Dieu chinh cong";
            lblDieuChinhNote.AutoSize = true;
            lblDieuChinhNote.Location = new Point(27, 172);
            lblDieuChinhNote.Size = new Size(618, 20);
            lblDieuChinhNote.Text = "Goi y: dung tab nay cho cac truong hop quen check-in/check-out, sai gio cong, can bo sung cong.";
            btnGuiDieuChinh.Location = new Point(27, 116);
            btnGuiDieuChinh.Size = new Size(175, 38);
            btnGuiDieuChinh.Text = "Gui yeu cau dieu chinh";
            btnGuiDieuChinh.Click += btnGuiDieuChinh_Click;
            txtDieuChinh.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            txtDieuChinh.Location = new Point(27, 51);
            txtDieuChinh.Multiline = true;
            txtDieuChinh.Size = new Size(1122, 49);
            lblDieuChinh.AutoSize = true;
            lblDieuChinh.Location = new Point(27, 28);
            lblDieuChinh.Text = "Mo ta yeu cau dieu chinh cong cua ban";
            AutoScaleDimensions = new SizeF(8F, 20F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(1184, 761);
            Controls.Add(tabMain);
            Controls.Add(pnlTop);
            MinimumSize = new Size(980, 680);
            Name = "FrmDonTuCaNhan";
            Text = "Don tu cua toi";
            Load += FrmDonTuCaNhan_Load;
            pnlTop.ResumeLayout(false);
            pnlTop.PerformLayout();
            tabMain.ResumeLayout(false);
            tabNghiPhep.ResumeLayout(false);
            tabNghiPhep.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)dgvNghiPhep).EndInit();
            ((System.ComponentModel.ISupportInitialize)nudTongSoNgay).EndInit();
            tabTangCa.ResumeLayout(false);
            tabTangCa.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)dgvTangCa).EndInit();
            tabDieuChinh.ResumeLayout(false);
            tabDieuChinh.PerformLayout();
            ResumeLayout(false);
        }
    }
}
