namespace HRM.Winform.Forms.CaNhan
{
    partial class FrmHoSoCaNhan
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private Panel pnlHeader;
        private Label lblTitle;
        private Button btnDoiMatKhau;
        private Button btnDangKyKhuonMat;
        private Panel pnlInfo;
        private Label lblHoTenTitle;
        private Label lblHoTenValue;
        private Label lblMaNhanVienTitle;
        private Label lblMaNhanVienValue;
        private Label lblPhongBanTitle;
        private Label lblPhongBanValue;
        private Label lblChucVuTitle;
        private Label lblChucVuValue;
        private Label lblNgayVaoLamTitle;
        private Label lblNgayVaoLamValue;
        private Label lblTrangThaiTitle;
        private Label lblTrangThaiValue;
        private PictureBox picKhuonMatMau;
        private Label lblFaceStatusTitle;
        private Label lblFaceStatusValue;
        private Label lblFaceCapturedTitle;
        private Label lblFaceCapturedValue;
        private Label lblFaceAssetTitle;
        private Label lblFaceAssetValue;
        private Label lblFaceRequestTitle;
        private Label lblFaceRequestValue;
        private Panel pnlContact;
        private Label lblSoDienThoai;
        private TextBox txtSoDienThoai;
        private Label lblEmail;
        private TextBox txtEmail;
        private Label lblDiaChi;
        private TextBox txtDiaChi;
        private Label lblCCCD;
        private TextBox txtCCCD;
        private Button btnLuu;

        private void InitializeComponent()
        {
            pnlHeader = new Panel();
            btnDangKyKhuonMat = new Button();
            btnDoiMatKhau = new Button();
            lblTitle = new Label();
            pnlInfo = new Panel();
            lblTrangThaiValue = new Label();
            lblTrangThaiTitle = new Label();
            lblNgayVaoLamValue = new Label();
            lblNgayVaoLamTitle = new Label();
            lblChucVuValue = new Label();
            lblChucVuTitle = new Label();
            lblPhongBanValue = new Label();
            lblPhongBanTitle = new Label();
            lblMaNhanVienValue = new Label();
            lblMaNhanVienTitle = new Label();
            lblHoTenValue = new Label();
            lblHoTenTitle = new Label();
            picKhuonMatMau = new PictureBox();
            lblFaceStatusTitle = new Label();
            lblFaceStatusValue = new Label();
            lblFaceCapturedTitle = new Label();
            lblFaceCapturedValue = new Label();
            lblFaceAssetTitle = new Label();
            lblFaceAssetValue = new Label();
            lblFaceRequestTitle = new Label();
            lblFaceRequestValue = new Label();
            pnlContact = new Panel();
            btnLuu = new Button();
            txtCCCD = new TextBox();
            lblCCCD = new Label();
            txtDiaChi = new TextBox();
            lblDiaChi = new Label();
            txtEmail = new TextBox();
            lblEmail = new Label();
            txtSoDienThoai = new TextBox();
            lblSoDienThoai = new Label();
            pnlHeader.SuspendLayout();
            pnlInfo.SuspendLayout();
            pnlContact.SuspendLayout();
            SuspendLayout();
            pnlHeader.Controls.Add(btnDangKyKhuonMat);
            pnlHeader.Controls.Add(btnDoiMatKhau);
            pnlHeader.Controls.Add(lblTitle);
            pnlHeader.Dock = DockStyle.Top;
            pnlHeader.Padding = new Padding(24, 20, 24, 16);
            pnlHeader.Size = new Size(1184, 92);
            btnDangKyKhuonMat.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            btnDangKyKhuonMat.Location = new Point(819, 28);
            btnDangKyKhuonMat.Size = new Size(178, 38);
            btnDangKyKhuonMat.Text = "Dang ky khuon mat";
            btnDangKyKhuonMat.Click += btnDangKyKhuonMat_Click;
            btnDoiMatKhau.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            btnDoiMatKhau.Location = new Point(1009, 28);
            btnDoiMatKhau.Size = new Size(148, 38);
            btnDoiMatKhau.Text = "Doi mat khau";
            btnDoiMatKhau.Click += btnDoiMatKhau_Click;
            lblTitle.AutoSize = true;
            lblTitle.Font = new Font("Segoe UI", 18F, FontStyle.Bold);
            lblTitle.Location = new Point(24, 25);
            lblTitle.Text = "Ho so ca nhan";
            pnlInfo.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Bottom;
            pnlInfo.Controls.Add(lblTrangThaiValue);
            pnlInfo.Controls.Add(lblTrangThaiTitle);
            pnlInfo.Controls.Add(lblNgayVaoLamValue);
            pnlInfo.Controls.Add(lblNgayVaoLamTitle);
            pnlInfo.Controls.Add(lblChucVuValue);
            pnlInfo.Controls.Add(lblChucVuTitle);
            pnlInfo.Controls.Add(lblPhongBanValue);
            pnlInfo.Controls.Add(lblPhongBanTitle);
            pnlInfo.Controls.Add(lblMaNhanVienValue);
            pnlInfo.Controls.Add(lblMaNhanVienTitle);
            pnlInfo.Controls.Add(lblHoTenValue);
            pnlInfo.Controls.Add(lblHoTenTitle);
            pnlInfo.Controls.Add(picKhuonMatMau);
            pnlInfo.Controls.Add(lblFaceStatusTitle);
            pnlInfo.Controls.Add(lblFaceStatusValue);
            pnlInfo.Controls.Add(lblFaceCapturedTitle);
            pnlInfo.Controls.Add(lblFaceCapturedValue);
            pnlInfo.Controls.Add(lblFaceAssetTitle);
            pnlInfo.Controls.Add(lblFaceAssetValue);
            pnlInfo.Controls.Add(lblFaceRequestTitle);
            pnlInfo.Controls.Add(lblFaceRequestValue);
            pnlInfo.Location = new Point(24, 116);
            pnlInfo.Padding = new Padding(24);
            pnlInfo.Size = new Size(551, 444);
            lblTrangThaiValue.AutoSize = true;
            lblTrangThaiValue.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
            lblTrangThaiValue.Location = new Point(283, 194);
            lblTrangThaiValue.Text = "--";
            lblTrangThaiTitle.AutoSize = true;
            lblTrangThaiTitle.Location = new Point(283, 171);
            lblTrangThaiTitle.Text = "Trang thai";
            picKhuonMatMau.BackColor = Color.FromArgb(241, 245, 249);
            picKhuonMatMau.Location = new Point(27, 244);
            picKhuonMatMau.Size = new Size(96, 96);
            picKhuonMatMau.SizeMode = PictureBoxSizeMode.Zoom;
            lblFaceStatusTitle.AutoSize = true;
            lblFaceStatusTitle.Location = new Point(145, 244);
            lblFaceStatusTitle.Text = "Trang thai khuon mat";
            lblFaceStatusValue.AutoSize = true;
            lblFaceStatusValue.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
            lblFaceStatusValue.Location = new Point(145, 267);
            lblFaceStatusValue.Text = "--";
            lblFaceCapturedTitle.AutoSize = true;
            lblFaceCapturedTitle.Location = new Point(145, 302);
            lblFaceCapturedTitle.Text = "Dang ky luc";
            lblFaceCapturedValue.AutoSize = true;
            lblFaceCapturedValue.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            lblFaceCapturedValue.Location = new Point(145, 323);
            lblFaceCapturedValue.Text = "--";
            lblFaceAssetTitle.AutoSize = true;
            lblFaceAssetTitle.Location = new Point(145, 346);
            lblFaceAssetTitle.Text = "Tai nguyen nhan dien";
            lblFaceAssetValue.AutoSize = true;
            lblFaceAssetValue.Font = new Font("Segoe UI", 9.5F, FontStyle.Bold);
            lblFaceAssetValue.Location = new Point(145, 367);
            lblFaceAssetValue.Text = "--";
            lblFaceRequestTitle.AutoSize = true;
            lblFaceRequestTitle.Location = new Point(145, 392);
            lblFaceRequestTitle.Text = "Dang ky lai";
            lblFaceRequestValue.AutoSize = true;
            lblFaceRequestValue.Font = new Font("Segoe UI", 9.5F, FontStyle.Bold);
            lblFaceRequestValue.Location = new Point(145, 413);
            lblFaceRequestValue.Text = "--";
            lblNgayVaoLamValue.AutoSize = true;
            lblNgayVaoLamValue.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
            lblNgayVaoLamValue.Location = new Point(27, 194);
            lblNgayVaoLamValue.Text = "--";
            lblNgayVaoLamTitle.AutoSize = true;
            lblNgayVaoLamTitle.Location = new Point(27, 171);
            lblNgayVaoLamTitle.Text = "Ngay vao lam";
            lblChucVuValue.AutoSize = true;
            lblChucVuValue.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
            lblChucVuValue.Location = new Point(283, 121);
            lblChucVuValue.Text = "--";
            lblChucVuTitle.AutoSize = true;
            lblChucVuTitle.Location = new Point(283, 98);
            lblChucVuTitle.Text = "Chuc vu";
            lblPhongBanValue.AutoSize = true;
            lblPhongBanValue.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
            lblPhongBanValue.Location = new Point(27, 121);
            lblPhongBanValue.Text = "--";
            lblPhongBanTitle.AutoSize = true;
            lblPhongBanTitle.Location = new Point(27, 98);
            lblPhongBanTitle.Text = "Phong ban";
            lblMaNhanVienValue.AutoSize = true;
            lblMaNhanVienValue.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
            lblMaNhanVienValue.Location = new Point(283, 51);
            lblMaNhanVienValue.Text = "--";
            lblMaNhanVienTitle.AutoSize = true;
            lblMaNhanVienTitle.Location = new Point(283, 28);
            lblMaNhanVienTitle.Text = "Ma nhan vien";
            lblHoTenValue.AutoSize = true;
            lblHoTenValue.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
            lblHoTenValue.Location = new Point(27, 51);
            lblHoTenValue.Text = "--";
            lblHoTenTitle.AutoSize = true;
            lblHoTenTitle.Location = new Point(27, 28);
            lblHoTenTitle.Text = "Ho ten";
            pnlContact.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right | AnchorStyles.Bottom;
            pnlContact.Controls.Add(btnLuu);
            pnlContact.Controls.Add(txtCCCD);
            pnlContact.Controls.Add(lblCCCD);
            pnlContact.Controls.Add(txtDiaChi);
            pnlContact.Controls.Add(lblDiaChi);
            pnlContact.Controls.Add(txtEmail);
            pnlContact.Controls.Add(lblEmail);
            pnlContact.Controls.Add(txtSoDienThoai);
            pnlContact.Controls.Add(lblSoDienThoai);
            pnlContact.Location = new Point(605, 116);
            pnlContact.Padding = new Padding(24);
            pnlContact.Size = new Size(552, 392);
            btnLuu.Location = new Point(391, 323);
            btnLuu.Size = new Size(134, 40);
            btnLuu.Text = "Luu thay doi";
            btnLuu.Click += btnLuu_Click;
            txtCCCD.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            txtCCCD.Location = new Point(27, 266);
            txtCCCD.Size = new Size(498, 27);
            lblCCCD.AutoSize = true;
            lblCCCD.Location = new Point(27, 243);
            lblCCCD.Text = "CCCD";
            txtDiaChi.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            txtDiaChi.Location = new Point(27, 187);
            txtDiaChi.Size = new Size(498, 27);
            lblDiaChi.AutoSize = true;
            lblDiaChi.Location = new Point(27, 164);
            lblDiaChi.Text = "Dia chi";
            txtEmail.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            txtEmail.Location = new Point(27, 108);
            txtEmail.Size = new Size(498, 27);
            lblEmail.AutoSize = true;
            lblEmail.Location = new Point(27, 85);
            lblEmail.Text = "Email";
            txtSoDienThoai.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            txtSoDienThoai.Location = new Point(27, 50);
            txtSoDienThoai.Size = new Size(498, 27);
            lblSoDienThoai.AutoSize = true;
            lblSoDienThoai.Location = new Point(27, 27);
            lblSoDienThoai.Text = "So dien thoai";
            AutoScaleDimensions = new SizeF(8F, 20F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(1184, 761);
            Controls.Add(pnlContact);
            Controls.Add(pnlInfo);
            Controls.Add(pnlHeader);
            MinimumSize = new Size(980, 680);
            Name = "FrmHoSoCaNhan";
            Text = "Ho so ca nhan";
            Load += FrmHoSoCaNhan_Load;
            pnlHeader.ResumeLayout(false);
            pnlHeader.PerformLayout();
            pnlInfo.ResumeLayout(false);
            pnlInfo.PerformLayout();
            pnlContact.ResumeLayout(false);
            pnlContact.PerformLayout();
            ResumeLayout(false);
        }
    }
}
